package fr.uga.iut2.genconf.vue.gui;


import fr.uga.iut2.genconf.modele.Conference;

import fr.uga.iut2.genconf.modele.enums.StatusConference;


import java.util.ArrayList;
import java.util.Map;

public class VueModificationConference extends javax.swing.JPanel {
    private final GUI gui;
    private StatusConference statut;
    private Map<String, Conference> conferences;
    /**
     * Creates new form VueCreationUtilisateur
     */
    public VueModificationConference(GUI gui) {
        this.gui = gui;
        this.statut = StatusConference.Presentiel;
        // création de l'interface générée
        this.initComponents();


    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    public void initComponents() {

        this.removeAll();

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        comboBoxInputConference = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        distancielButton = new javax.swing.JRadioButton();
        presentielButton = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        buttonGroup = new javax.swing.ButtonGroup();
        boutons = new javax.swing.JRadioButton[2];

        setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Conférences :");

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("CONFIGURER STATUT CONFÉRENCE");

        comboBoxInputConference.setBackground(new java.awt.Color(255, 255, 255));
        comboBoxInputConference.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        comboBoxInputConference.setForeground(new java.awt.Color(0, 0, 0));
        try{
            this.conferences.forEach((key, value) -> comboBoxInputConference.addItem(value.getNom()));
        }catch (Exception e){}




        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Statut :");


        distancielButton.setBackground(new java.awt.Color(204, 204, 204));
        distancielButton.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        distancielButton.setForeground(new java.awt.Color(0, 0, 0));
        distancielButton.setText("DISTANCIEL");
        distancielButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setType(StatusConference.Distanciel);
            }
        });
        buttonGroup.add(distancielButton);

        presentielButton.setSelected(true);
        presentielButton.setBackground(new java.awt.Color(204, 204, 204));
        presentielButton.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        presentielButton.setForeground(new java.awt.Color(0, 0, 0));
        presentielButton.setText("PRESENTIEL");
        presentielButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setType(StatusConference.Presentiel);
            }
        });
        buttonGroup.add(presentielButton);
        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("ANNULER");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annulerActionPerformed(evt);
            }
        });;

        jButton2.setBackground(new java.awt.Color(153, 153, 153));
        jButton2.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("Valider");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(124, 124, 124))
                        .addGroup(layout.createSequentialGroup()
                                .addGap(103, 103, 103)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(51, 51, 51)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(presentielButton)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(distancielButton))
                                                        .addComponent(comboBoxInputConference, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap(81, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(comboBoxInputConference, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(distancielButton)
                                        .addComponent(presentielButton))
                                .addGap(106, 106, 106)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton1)
                                        .addComponent(jButton2))
                                .addContainerGap(124, Short.MAX_VALUE))
        );


    }

    private void creerActionPerformed(java.awt.event.ActionEvent evt) {
        int numLigne = comboBoxInputConference.getSelectedIndex();
        //Conference util = conf.get(numLigne);
        //gui.controleur.changerStatusConference(util.getNom(), this.statut);
    }

    private void annulerActionPerformed(java.awt.event.ActionEvent evt) {
        gui.controleur.consulterConferences();
    }

    private void setType(StatusConference statut){
        this.statut = statut;
    }

    public void setParentConferences(Map<String,Conference> conferences){
        this.conferences = conferences;
    }


    private javax.swing.JComboBox<String> comboBoxInputConference;
    private javax.swing.JRadioButton distancielButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton presentielButton;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JRadioButton [] boutons;

}
