package fr.uga.iut2.genconf.vue.gui;

import fr.uga.iut2.genconf.modele.Conference;
import fr.uga.iut2.genconf.modele.Utilisateur;
import fr.uga.iut2.genconf.vue.gui.rootage.Roots;

import java.awt.*;
import java.util.*;
import java.util.stream.Collectors;
import javax.swing.*;


public class VuePrincipale extends javax.swing.JFrame {
    private final GUI gui;


    /**
     * Creates new form VuePrincipale
     */
    public VuePrincipale(GUI gui) {
        this.gui = gui;

        // création de l'interface générée
        this.initComponents();
    }



    protected void afficher() {
        this.setSize(700,550);
        this.setVisible(true);
    }

    protected void ajouterVue(JPanel vue, Roots root) {

        CardLayout cLayout = (CardLayout) this.getContentPane().getLayout();
        cLayout.addLayoutComponent(vue, root.toString());
        this.add(vue);
    }

    protected void afficherVue(Roots root) {
        CardLayout cLayout = (CardLayout) getContentPane().getLayout();
        cLayout.show(this.getContentPane(), root.toString());
    }

    protected void fermer() {
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    public void initComponents() {


        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu0 = new javax.swing.JMenu();
        menuRetourMenu = new javax.swing.JMenuItem();
        jMenu000 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem4 = new javax.swing.JMenuItem();
        modifConf = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("GenConf");
        getContentPane().setLayout(new java.awt.CardLayout());

        jMenu0.setText("Application");
        menuRetourMenu.setText("Accueil");
        menuRetourMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gui.controleur.consulterConferences();
            }
        });


        jMenu000.setText("Utilisateurs");
        jMenu000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionMenuConsulterUtilisateurs(evt);
            }
        });


        jMenu0.add(jMenu000);
        jMenu0.add(menuRetourMenu);
        jMenu0.add(jSeparator1);
        jMenuItem4.setText("Quitter");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionMenuQuitter(evt);
            }
        });
        jMenu0.add(jMenuItem4);


        jMenuBar1.add(jMenu0);
        jMenu1.setText("Gestion");

        jMenuItem1.setText("Créer une conférence");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionMenuCreationConference(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem3.setText("Créer un utilisateur");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionMenuCreationUtilisateur(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        modifConf.setText("Changer Statut Conference");
        modifConf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionMenuModificationConference(evt);
            }
        });
        jMenu1.add(modifConf);


        jMenuBar1.add(jMenu1);
        jMenuBar1.setFont(new Font("Calibri", Font.PLAIN, 14));
        setJMenuBar(jMenuBar1);



        addWindowListener(new java.awt.event.WindowListener() {
            public void windowOpened(java.awt.event.WindowEvent e) {}
            public void windowClosed(java.awt.event.WindowEvent e) {}
            public void windowIconified(java.awt.event.WindowEvent e) {}
            public void windowDeiconified(java.awt.event.WindowEvent e) {}
            public void windowActivated(java.awt.event.WindowEvent e) {}
            public void windowDeactivated(java.awt.event.WindowEvent e) {}
            public void windowClosing(java.awt.event.WindowEvent e) {
                actionQuitter(e);
                System.exit(0);
            }
        });

        pack();
    }

    private void actionMenuCreationUtilisateur(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionMenuCreationUtilisateur
        this.gui.actionCreerUtilisateur();
    }//GEN-LAST:event_actionMenuCreationUtilisateur

    private void actionMenuModificationConference(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionMenuCreationUtilisateur
        this.gui.definirStatusConference(null);
    }

    private void actionMenuCreationConference(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionMenuCreationConference
        this.gui.actionCreerConference();
    }

    private void actionMenuConsulterUtilisateurs(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionMenuCreationConference
        this.gui.controleur.consulterUtilisateurs();
    }

    private void actionMenuQuitter(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionMenuQuitter
        this.gui.actionTerminer();
    }//GEN-LAST:event_actionMenuQuitter




    private void actionQuitter(java.awt.event.WindowEvent windowEvent) {
        this.gui.actionTerminer();
    }

    private static Object[] utilisateursToStringArray(Utilisateur utilisateur) {
        return new Object[]{utilisateur.getNom()};
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    //
    private javax.swing.JMenu jMenu0;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem menuRetourMenu;
    private javax.swing.JMenuItem jMenu000;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem modifConf;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
