package fr.uga.iut2.genconf.vue.gui.rootage;

public enum Roots {
    VUE_ETAT,
    VUE_DEFAUT,
    VUE_CREATION_CONF,
    VUE_CREATION_SESSION,
    VUE_CREATION_USER,
    VUE_CREATION_COMMUNICATION,
    VUE_CREATION_SPEAKER,
    VUE_CREATION_CHAIRMAN,
    VUE_ASSOCIER_ARTICLE,
    VUE_AFFICHAGE_CONFERENCE,
    VUE_AFFICHAGE_SESSION,
    VUE_AFFICHAGE_COMMUNICATION,
    VUE_AFFICHAGE_UTILISATEURS,
    VUE_AFFICHAGE_UTILISATEUR,
    VUE_MODIFICATION_CONFERENCE,
}
